
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Set these values by hand
path_prefix = '/data14/smkim';
subjects = {'S61'};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

TS_PER_SEC = 1e4;

for s = 1:numel(subjects)
  load(sprintf('%s/%s/%s_session.mat',path_prefix,subjects{s},subjects{s}));
  for i = 1:numel(session)

    %{
    disp([char(10) sprintf('subject %s day %d epoch %s (%s - %s)', ...
        session(i).subject,session(i).day,session(i).epoch, ...
        session(i).tstart,session(i).tend)]);
    mpeg_filename = sprintf('%s/%s/behavior/%s_day%d.mpeg', ...
        path_prefix,subjects{s},subjects{s},session(i).day);
    mpegoffset_filename = sprintf('%s/%s/behavior/%s_day%d.mpegoffset', ...
        path_prefix,subjects{s},subjects{s},session(i).day);
    timestamp_filename = sprintf('%s/%s/behavior/%s_day%d.videotimestamps', ...
        path_prefix,subjects{s},subjects{s},session(i).day);
    % run nspike_fixpos starting 1 second before epoch start time
    system(sprintf(['rm -f /tmp/tmp1.pos; ~/nspike_fixpos -p %s -f64 %s ' ...
        '-t %s -thresh 200 -speed 20 -skip 2 -tstart %s -tend %s ' ...
        '-o /tmp/tmp1.pos &'],mpeg_filename,mpegoffset_filename, ...
        timestamp_filename,ts2str(session(i).timerange(1) - TS_PER_SEC), ...
        ts2str(session(i).timerange(1))));
    % run nspike_fixpos until 1 second past epoch end time
    system(sprintf(['rm -f /tmp/tmp2.pos; ~/nspike_fixpos -p %s -f64 %s ' ...
        '-t %s -thresh 200 -speed 20 -skip 2 -tstart %s -tend %s ' ...
        '-o /tmp/tmp2.pos &'],mpeg_filename,mpegoffset_filename, ...
        timestamp_filename,ts2str(session(i).timerange(end)), ...
        ts2str(session(i).timerange(end) + TS_PER_SEC)));
    %}

    % load timestamps struct array into workspace
    load(sprintf('%s/%s/behavior/%s_day%d_videotimestamps.mat', ...
        path_prefix,subjects{s},subjects{s},session(i).day));
    figure;
    subplot(2,1,1);
    title(sprintf('subject %s day %d epoch %s start: %s', ...
        session(i).subject,session(i).day,session(i).epoch, ...
        session(i).tstart));
    line(timestamps,zeros(size(timestamps)),'Marker','o','Color','k', ...
        'LineStyle','none');
    line([session(i).timerange(1) session(i).timerange(1)],[-1 1], ...
        'LineStyle','-','Color','r');
    set(gca,'XLim',[session(i).timerange(1) - 1e4, ...
        session(i).timerange(1) + 1e4]);
    subplot(2,1,2);    
    title(sprintf('subject %s day %d epoch %s end: %s', ...
        session(i).subject,session(i).day,session(i).epoch, ...
        session(i).tend));
    line(timestamps,zeros(size(timestamps)),'Marker','o','Color','k', ...
        'LineStyle','none');
    line([session(i).timerange(end) session(i).timerange(end)],[-1 1], ...
        'LineStyle','-','Color','r');
    set(gca,'XLim',[session(i).timerange(end) - 1e4, ...
        session(i).timerange(end) + 1e4]);
    pause;
    delete(gcf);

  end
end
