Description of Rdemo
Home > chronux_1_50 > old > locfit_wrap > rlink > Rdemo.m
Rdemo
PURPOSE
% Connecting MATLAB to R
SYNOPSIS
This is a script file.
DESCRIPTION
% Connecting MATLAB to R
 The statistical programming language R has a COM interface. We can use
 this to execute R commands from within MATLAB.
CROSS-REFERENCE INFORMATION
This function calls:
closeR CLOSER Close connection to R server process
evalR EVALR Run an R command.
getRdata GETRDATA Copies an R variable to MATLAB.
openR OPENR Connect to an R server process.
putRdata PUTRDATA Copies MATLAB data to an R variable.
This function is called by:
SOURCE CODE
%% Connecting MATLAB to R
% The statistical programming language R has a COM interface. We can use
% this to execute R commands from within MATLAB.
%% Connect to an R Session
openR
%% Push data into R
a = 1:10;
putRdata('a',a)
%% Run a simple R command
b = evalR('a^2');
%% Run a series of commands and grab the result
evalR('b <- a^2');
evalR('c <- b + 1');
c = getRdata('c');
%% Close the connection
closeR