% timefilterscript



% preparatory
stopping         =  {'kk_getstoptimes', '($stopstate == -1)'};
starting         =  {'kk_getstoptimes', '($stopstate == 1)'};

% gammac CA1   
gc_ca1 = {'kk_getconstimes', '($cons == 1)', 'gammaccons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};


% theta waves episodes
theta_asc         =  {'kk_gettwavetimes', '($twave == 1)'};
theta_desc       =  {'kk_gettwavetimes', '($twave == -1)'};


% delta waves episodes
pospeak         =  {'kk_getdwavetimes', '($dwave == 1)', 'pospeak','minamp_z',[]};
negtrough       =  {'kk_getdwavetimes', '($dwave == 1)', 'negtrough', 'minamp_z',[]};
pospeak_1       =  {'kk_getdwavetimes', '($dwave == 1)', 'pospeak','minamp_z',1};
negtrough_1     =  {'kk_getdwavetimes', '($dwave == 1)', 'negtrough', 'minamp_z',1};
pospeak_2       =  {'kk_getdwavetimes', '($dwave == 1)', 'pospeak','minamp_z',2};
negtrough_2     =  {'kk_getdwavetimes', '($dwave == 1)', 'negtrough', 'minamp_z',2};

% gamma episodes
g1episode =  {'kk_getepisodetimes', '($episode == 1)', 'gamepisode','periodnum',1,'timescalenum',7};
g2episode =  {'kk_getepisodetimes', '($episode == 1)', 'gamepisode', 'periodnum',2,'timescalenum',7};


% exclusion
norip =  {'kk_getconstimes', '($cons == 0)', 'ripplescons',1,...
    'consensus_numtets',3,...
    'minthresh',2,'exclusion_dur',0,'maxvelocity',4,'minvelocity',0};

nogf_ca3dg = {'kk_getconstimes', '($cons == 0)', 'gammafcons',2,...
    'consensus_numtets',2,...
    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};

nogl_ca3dg = {'kk_getconstimes', '($cons == 0)', 'gammalcons',2,...
    'consensus_numtets',2,...
    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};

nogf_ca1 = {'kk_getconstimes', '($cons == 0)', 'gammafcons',1,...
    'consensus_numtets',3,...
    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};

nosr_ca1 = {'kk_getconstimes', '($cons == 0)', 'slowripplescons',1,...
        'consensus_numtets',3,...
        'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};

nosr_ca3 = {'kk_getconstimes', '($cons == 0)', 'slowripplescons',3,...
        'consensus_numtets',2,...
        'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};    

nobeta_ca3 = {'kk_getconstimes', '($cons == 0)', 'betascons',3,...
        'consensus_numtets',2,...
        'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};     
nobeta_ca3dg = {'kk_getconstimes', '($cons == 0)', 'betascons',2,...
        'consensus_numtets',2,...
        'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};      
nogf_ca3 = {'kk_getconstimes', '($cons == 0)', 'gammafcons',3,...
    'consensus_numtets',2,...
    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};

    
% inclusion   

% ripple
rip2 =  {'kk_getconstimes', '($cons == 1)', 'ripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',4,'minvelocity',0};      
rip2excl =  {'kk_getconstimes', '($cons == 1)', 'ripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',2,'exclusion_dur',0.5,'maxvelocity',4,'minvelocity',0};                      
rip3 =  {'kk_getconstimes', '($cons == 1)', 'ripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',4,'minvelocity',0};                      
rip4 =  {'kk_getconstimes', '($cons == 1)', 'ripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',4,'minvelocity',0};      
                
rip6 =  {'kk_getconstimes', '($cons == 1)', 'ripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',6,'exclusion_dur',0,'maxvelocity',4,'minvelocity',0};                    
rip7 =  {'kk_getconstimes', '($cons == 1)', 'ripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',7,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};  

erip4 =  {'kk_getconstimes', '($cons == 1)', 'ripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',10,'minvelocity',0};                 
rip7allvel =  {'kk_getconstimes', '($cons == 1)', 'ripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',7,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0}; 
                
    
% CA3 -- 
% rip
rip2_ca3b = {'kk_getconstimes', '($cons == 1)', 'ripplescons',5,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};                
                
                
% CA3 -- 
% gammaf
gf2_ca3 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',3,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
gf3_ca3 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',3,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
gf4_ca3 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',3,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};

% CA3b -- 
% gammaf
gf2_ca3b = {'kk_getconstimes', '($cons == 1)', 'gammafcons',5,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
gf3_ca3b = {'kk_getconstimes', '($cons == 1)', 'gammafcons',5,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
gf4_ca3b = {'kk_getconstimes', '($cons == 1)', 'gammafcons',5,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};                
                
                
                
 % beta
beta2_ca3 = {'kk_getconstimes', '($cons == 1)', 'betascons',3,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
beta3_ca3 = {'kk_getconstimes', '($cons == 1)', 'betascons',3,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
beta4_ca3 = {'kk_getconstimes', '($cons == 1)', 'betascons',3,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4}; 
                
% gammal   
    %ca1
gl2_ca1_ripok = {'kk_getconstimes', '($cons == 1)', 'gammalcons',1,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};      
    % ca3
gl2_ca3 = {'kk_getconstimes', '($cons == 1)', 'gammalcons',3,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};  
    % ca3-dg
gl2_ca3dg = {'kk_getconstimes', '($cons == 1)', 'gammalcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};                 
% gammal                
gl2_ca3b = {'kk_getconstimes', '($cons == 1)', 'gammalcons',5,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};  
                
                
                
                
% wides  
wides2_ca3 = {'kk_getconstimes', '($cons == 1)', 'widescons',3,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};  
% wides  
wides2_ca3b = {'kk_getconstimes', '($cons == 1)', 'widescons',5,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};                  
                
                
                
% slow ripple
sr2_ca3 = {'kk_getconstimes', '($cons == 1)', 'slowripplescons',3,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};         
sr3_ca3 = {'kk_getconstimes', '($cons == 1)', 'slowripplescons',3,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};                    
sr4_ca3 = {'kk_getconstimes', '($cons == 1)', 'slowripplescons',3,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};    
                
                

                
                
% gammaf CA3-DG   

gf2_ca3dg_min10 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',10,...           
                    'exclusion2','ripplescons',1,3,2,0,4};

gf2_ca3dg = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gf2_ca3dg_ripok = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};                
                
gf3_ca3dg = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gf3_ca3dg_ripok = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};                
                
gf4_ca3dg = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gf4_ca3dg_ripok = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};
                
                
                
    % w/ 25,50,75 CA1-DG/CA3b percentile coherence
gf2_ca3dg_25 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4,'coherence',25,[1 2]};
gf2_ca3dg_50 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4,'coherence',50,[1 2]};
gf2_ca3dg_75 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4,'coherence',75,[1 2]};                

% gammaf CA1                
gf2_ca1 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gf3_ca1 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gf4_ca1 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};                
               
    % gammaf (CA1) w/ 25,50,75 CA1-DG/CA3b percentile coherence                
gf2_ca1_25 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4,'coherence',25,[1 2]};
gf2_ca1_50 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4,'coherence',50,[1 2]};
gf2_ca1_75 = {'kk_getconstimes', '($cons == 1)', 'gammafcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4,'coherence',75,[1 2]};   

% wide (65-250 Hz) power in CA3-DG                      
wides2_ca3dg =  {'kk_getconstimes', '($cons == 1)', 'widescons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};                
wides3_ca3dg =  {'kk_getconstimes', '($cons == 1)', 'widescons',2,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};     
wides4_ca3dg =  {'kk_getconstimes', '($cons == 1)', 'widescons',2,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};    
 % beta
beta2_ca3dg = {'kk_getconstimes', '($cons == 1)', 'betascons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
beta3_ca3dg = {'kk_getconstimes', '($cons == 1)', 'betascons',2,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
beta4_ca3dg = {'kk_getconstimes', '($cons == 1)', 'betascons',2,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};                 
                
                
                

                
% CA1 slow ripple                       
sr2_ca1 =  {'kk_getconstimes', '($cons == 1)', 'slowripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
sr3_ca1 =  {'kk_getconstimes', '($cons == 1)', 'slowripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
sr4_ca1 =  {'kk_getconstimes', '($cons == 1)', 'slowripplescons',1,...
                    'consensus_numtets',3,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
     % coherence additions
sr2_ca1_50ca2 =  {'kk_getconstimes', '($cons == 1)', 'slowripplescons',1,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4,'coherence',50,[5]};
sr2_ca1_50ca3dg =  {'kk_getconstimes', '($cons == 1)', 'slowripplescons',1,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4,'coherence',50,[1 2]};       
sr2_ca1_75ca3dg =  {'kk_getconstimes', '($cons == 1)', 'slowripplescons',1,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4,'coherence',75,[1 2]};                       
                
                
% CA1 high gamma                       
gh2_ca1 =  {'kk_getconstimes', '($cons == 1)', 'gammahcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gh3_ca1 =  {'kk_getconstimes', '($cons == 1)', 'gammahcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gh4_ca1 =  {'kk_getconstimes', '($cons == 1)', 'gammahcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
         
% CA1 low gamma                       
gl2_ca1 =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gl3_ca1 =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gl4_ca1 =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',1,...
                    'consensus_numtets',3,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
                
% CA3-DG low gamma                       
gl2_ca3dg =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gl2_ca3dg_ripok =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0};                
gl3_ca3dg =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gl4_ca3dg =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',2,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4}; 
                

%  CA3 low gamma                       
gl2_ca3 =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',3,...
                    'consensus_numtets',2,...
                    'minthresh',2,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gl3_ca3 =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',3,...
                    'consensus_numtets',2,...
                    'minthresh',3,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
gl4_ca3 =  {'kk_getconstimes', '($cons == 1)', 'gammalcons',3,...
                    'consensus_numtets',2,...
                    'minthresh',4,'exclusion_dur',0,'maxvelocity',inf,'minvelocity',0,...           
                    'exclusion2','ripplescons',1,3,2,0,4};
                
% well
well0 = {'kk_getwelltimes','($nearwell == 1)', 0} ;
well2 = {'kk_getwelltimes','($nearwell == 1)', 2} ;
well4 = {'kk_getwelltimes','($nearwell == 1)', 4} ;
well6 = {'kk_getwelltimes','($nearwell == 1)', 6} ;
well8 = {'kk_getwelltimes','($nearwell == 1)', 8} ;
nonwell0 = {'kk_getwelltimes','($nearwell == 0)', 0} ;   % used in decoding
nonwell4 = {'kk_getwelltimes','($nearwell == 0)', 4} ;
nonwell6 = {'kk_getwelltimes','($nearwell == 0)', 6} ;               
nonwell8 = {'kk_getwelltimes','($nearwell == 0)', 8} ;   
nonwell10 = {'kk_getwelltimes','($nearwell == 0)', 10} ;   
nonwell12 = {'kk_getwelltimes','($nearwell == 0)', 12} ;
nonwell20 = {'kk_getwelltimes','($nearwell == 0)', 20} ;
nonwell25 = {'kk_getwelltimes','($nearwell == 0)', 25} ;
nonwell30 = {'kk_getwelltimes','($nearwell == 0)', 30} ;
nonwell40 = {'kk_getwelltimes','($nearwell == 0)', 40} ;

% centerT  (linpos)
centerT_10 = {'kk_getlinpostimes','($linpos > 66) & ($linpos < 86)'} ;
centerT_15 = {'kk_getlinpostimes','($linpos > 61) & ($linpos < 91)'} ;
centerT_20 = {'kk_getlinpostimes','($linpos > 56) & ($linpos < 96)'} ;
% junctions (improvement over the above)
centerjunct_10 = {'kk_getwjunctiontimes','($junction == 1)','center',10} ;
rightjunct_10 = {'kk_getwjunctiontimes','($junction == 1)','right',10} ;
leftjunct_10 = {'kk_getwjunctiontimes','($junction == 1)','left',10} ;
centerjunct_15 = {'kk_getwjunctiontimes','($junction == 1)','center',15} ;
rightjunct_15 = {'kk_getwjunctiontimes','($junction == 1)','right',15} ;
leftjunct_15 = {'kk_getwjunctiontimes','($junction == 1)','left',15} ;
centerjunct_5 = {'kk_getwjunctiontimes','($junction == 1)','center',5} ;
rightjunct_5 = {'kk_getwjunctiontimes','($junction == 1)','right',5} ;
leftjunct_5 = {'kk_getwjunctiontimes','($junction == 1)','left',5} ;

% velocity        
fullepoch = {'kk_get2dstate', '((abs($velocity) >= 0))'};
locomotion = {'kk_get2dstate', '((abs($velocity) > 4))'};
moving2 = {'kk_get2dstate', '((abs($velocity) > 2))'};
highspeed10 = {'kk_get2dstate', '((abs($velocity) > 10))'};
highspeed20 = {'kk_get2dstate', '((abs($velocity) > 20))'};
immobile = {'kk_get2dstate', '($immobility == 1)','immobility_velocity',4,'immobility_buffer',0};
immobile2 = {'kk_get2dstate', '($immobility == 1)','immobility_velocity',4,'immobility_buffer',2}; % notice 2 s buffer
nonimmobile2 = {'kk_get2dstate', '($immobility == 0)','immobility_velocity',4,'immobility_buffer',2}; % notice 2 s buffer
immobile3 = {'kk_get2dstate', '($immobility == 1)','immobility_velocity',4,'immobility_buffer',3}; % notice 3 s buffer
immobile5 = {'kk_get2dstate', '($immobility == 1)','immobility_velocity',4,'immobility_buffer',5}; % notice 3 s buffer
early4immobile = {'kk_get2dstate', '($immobility == 1)','immobility_velocity',4,'early_immobility',3}; % first 3 s of immobility velocity
early10immobile = {'kk_get2dstate', '($immobility == 1)','immobility_velocity',10,'early_immobility',3}; % first 3 s of immobility velocity


hi = highspeed10;
lo = immobile;
ripvel = {'kk_get2dstate', '((abs($velocity) < 4))'};
velunder10 = {'kk_get2dstate', '((abs($velocity) < 10))'};
velunder20 = {'kk_get2dstate', '((abs($velocity) < 20))'};
vel6b = {'kk_get2dstate', '(abs($velocity) < 6)'};
med = {'kk_get2dstate', '((abs($velocity) >= 4) & (abs($velocity) < 10) ) '};
vel4 = {'kk_get2dstate', '(abs($velocity) > 4)'};
vel5 = {'kk_get2dstate', '(abs($velocity) > 5)'};
vel6 = {'kk_get2dstate', '(abs($velocity) > 6)'};
vel8 = {'kk_get2dstate', '(abs($velocity) > 8)'};
vel10 = {'kk_get2dstate', '(abs($velocity) > 10)'};
vel16 = {'kk_get2dstate', '(abs($velocity) > 16)'};
vel20 = {'kk_get2dstate', '(abs($velocity) > 20)'};
vel24 = {'kk_get2dstate', '(abs($velocity) > 24)'};
vel25 = {'kk_get2dstate', '(abs($velocity) > 25)'};
vel30 = {'kk_get2dstate', '(abs($velocity) > 30)'};
vel32 = {'kk_get2dstate', '(abs($velocity) > 32)'};
vel40 = {'kk_get2dstate', '(abs($velocity) > 40)'};
velany = {'kk_get2dstate', '(abs($velocity) >= -99)'};p

% linear velocity
linvel4 = {'getlinvelocity','(abs($velocity) > 4)'};

% sleep
sleepc = {'kk_getsleep', '(($sleep == 1))',0};
nosleepc = {'kk_getsleep', '(($sleep == 0))',0};
sleepc_90 = {'kk_getsleep','(($sleep == 1))',90};  % 2 minute minimum duration
sleepc_2 = {'kk_getsleep','(($sleep == 1))',120};  % 2 minute minimum duration
sleepc_3 = {'kk_getsleep','(($sleep == 1))',180};  % 3 minute minimum duration

% waking
waking = {'kk_getwaking', '(($waking == 1))'};


% sia
SIA = {'kk_getsia', '($sia == 1)'};
noSIA = {'kk_getsia', '($sia == 0)'};
% recommended: {sia}  vs.  {nosia, sleepc_3, norem}

% lia
LIA = {'kk_getlia', '($lia == 1)'};
noLIA = {'kk_getlia', '($lia == 0)'};

% REM periods (rest box / sleep epochs only)
REM = {'kk_getrem', '($rem == 1)'};
noREM = {'kk_getrem', '($rem == 0)'};

% Low theta periods any epoch
lowtheta = {'kk_getlowtheta', '(($lowtheta == 1))'};

% VTE
vteperiod = {'kk_getVTEtimes', '(($vte == 1))'};

