Description of correlations
Home > chronux_1_50 > spikesort > correlations.m
correlations
PURPOSE
CORRELATIONS another temporary utility to show clusters
SYNOPSIS
function correlations(spikes, useassigns, show);
DESCRIPTION
    CORRELATIONS  another temporary utility to show clusters
       CORRELATIONS(SPIKES, [USEASSIGNS], [SHOW]);
CROSS-REFERENCE INFORMATION
This function calls:
pxcorr PXCORR Efficient cross-correlation for point process data.
This function is called by:
SpikeSortingDemo % Demonstration code for the spike sorter derived from the Fee et al.
SpikeSortingQuickReference %%%%%%%%%%%%%%%%%%%%%%%%%%%%% SORTING %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOURCE CODE
function correlations(spikes, useassigns, show);
%    CORRELATIONS  another temporary utility to show clusters
%       CORRELATIONS(SPIKES, [USEASSIGNS], [SHOW]);
%   Last Modified By: sbm on Fri Sep 16 07:03:16 2005
if (nargin < 2),
    if (isfield(spikes.hierarchy, 'assigns')),  useassigns = spikes.hierarchy.assigns;
    elseif (isfield(spikes.overcluster, 'assigns')), useassigns = spikes.overcluster.assigns;
    else useassigns = ones(size(spikes.waveforms,1),1);
    end
end
if (nargin < 3)
    list = unique(useassigns);
    show = list(1:min(5,length(list)));
end
K = length(show);
maxlag = 0.050;  % (msec);
for r = 1:K
    for c = r:K  % upper right triangle only (b/c symmetric)
        subplot(K,K,c+(r-1)*K);
        selectrow = find(useassigns == show(r));
        selectcol = find(useassigns == show(c));
        if ((length(selectrow) > 1) && (length(selectcol) > 1))
            [cross,lags] = pxcorr(spikes.spiketimes(selectrow), spikes.spiketimes(selectcol), 1000, maxlag);
            if (r == c),  cross(find(lags == 0)) = 0;  end;  % blank out autocorr peak
            bar(lags,cross,1.0);  shading flat;
            set(gca, 'XLim', [-maxlag, maxlag]);
        else
            cla;  % show blank if <= 1 pts
        end
        if (r == c),  ylabel(sprintf('Cluster #%d', show(r)));  end;
        if (r == 1),  title(sprintf('Cluster #%d', show(c)));  end;
    end
end