extractsleep2('/data12/mari/Egy/','egy','', '(isequal($type, ''sleep''))', ...
    'immobility',[10 0.5],'bimodal_study',0, ...
    'sleep',1, ...
    'rem',0,'rem_thresh',.7,'mindur_rem',1, ...
    'nrem',0,'nrem_thresh',.7,'mindur_nrem',0,  ...
    'spindle',1,'spindle_thresh',1,'mindur_spindle',0.5,  ...
    'sws',1,'sws_thresh',.5,'mindur_sws',1, 'mindur_down',.020,...
    'cortex',1)




          
          %(isequal($area, ''CA1''))
          
          
          
          
%            extractsleep2('/data12/kkay/Cha/','cha','', '(isequal($type, ''sleep''))', ...
%               'immobility',[10 0.5],'bimodal_study',0, ...
%               'sleep',1, ...
%               'rem',0,'rem_thresh',.7,'mindur_rem',1, ...
%               'nrem',0,'nrem_thresh',.7,'mindur_nrem',0,  ...
%               'spindle',1,'spindle_thresh',1,'mindur_spindle',0.5,  ...
%               'sws',0,'sws_thresh',0,'mindur_sws',1, ...
%               'cortex',0)