#!/bin/bash
#comps='aurora blizzard cyclone lightning monsoon sunshine tornado tsunami virga'
comps='aurora blizzard cyclone monsoon sunshine tornado tsunami virga '

for c in $comps; do
    echo  ========= $c =========
    # show my processes
#    ssh -x $c ps aux | grep chengs | grep -v sshd | grep -v "ps aux" | grep -v helper
    ssh -x $c ps aux | grep chengs | grep -v sshd | grep -v "ps aux" | grep -v helper | grep matlab
done
