Description of mtspecgramtrigc
Home > chronux_1_50 > continuous > mtspecgramtrigc.m
mtspecgramtrigc
PURPOSE
Multi-taper event triggered time-frequency spectrum - continuous process
SYNOPSIS
function [S,t,f,Serr]=mtspecgramtrigc(data,E,win,movingwin,params)
DESCRIPTION
 Multi-taper event triggered time-frequency spectrum - continuous process
 Usage:
 [S,t,f,Serr]=mtspecgramtrigc(data,E,win,movingwin,params)
 Input:
 Note units have to be consistent. Thus, if movingwin is in seconds, Fs
 has to be in Hz. see chronux.m for more information.
       data        (single channel data) -- required
       E           (event times) -- required
       win         (in the form [winl winr] i.e window around each event)
                                                 required
       movingwin         (in the form [window winstep] i.e length of moving
                                                 window and step size) -
                                                 required
                                                 Note that units for the windows have
                                                 to be consistent with
                                                 units of Fs
       params: structure with fields tapers, pad, Fs, fpass, err, trialave
       - optional
           tapers (precalculated tapers from dpss, or in the form [NW K] e.g [3 5]) -- optional. If not
                                                 specified, use [NW K]=[3 5]
            pad            (padding factor for the FFT) - optional (can take values -1,0,1,2...).
                    -1 corresponds to no padding, 0 corresponds to padding
                    to the next highest power of 2 etc.
                       e.g. For N = 500, if PAD = -1, we do not pad; if PAD = 0, we pad the FFT
                       to 512 points, if pad=1, we pad to 1024 points etc.
                       Defaults to 0.
           Fs   (sampling frequency) - optional. Default 1.
           fpass    (frequency band to be used in the calculation in the form
                                   [fmin fmax])- optional.
                                   Default all frequencies between 0 and Fs/2
           err  (error calculation [1 p] - Theoretical error bars; [2 p] - Jackknife error bars
                                   [0 p] or 0 - no error bars) - optional. Default 0.
           trialave (average over events when 1, don't average when 0) - optional. Default 0
 Output:
       S       (triggered spectrum in form time x frequency x events for trialave=0; or in the form time x frequency trialave=1)
       t       (times)
       f       (frequencies)
       Serr    (error bars) only for err(1)>=1
CROSS-REFERENCE INFORMATION
This function calls:
createdatamatc Helper function to create an event triggered matrix from univariate
mtspecgramc Multi-taper time-frequency spectrum - continuous process
change_row_to_column Helper routine to transform 1d arrays into column vectors that are needed
getparams Helper function to convert structure params to variables used by the
This function is called by:
testscript function testscript(pname,direction,movingwin,segave,params,fscorr)
spectraMBL2005
SOURCE CODE
function [S,t,f,Serr]=mtspecgramtrigc(data,E,win,movingwin,params)
% Multi-taper event triggered time-frequency spectrum - continuous process
%
% Usage:
%
% [S,t,f,Serr]=mtspecgramtrigc(data,E,win,movingwin,params)
% Input:
% Note units have to be consistent. Thus, if movingwin is in seconds, Fs
% has to be in Hz. see chronux.m for more information.
%       data        (single channel data) -- required
%       E           (event times) -- required
%       win         (in the form [winl winr] i.e window around each event)
%                                                 required
%       movingwin         (in the form [window winstep] i.e length of moving
%                                                 window and step size) -
%                                                 required
%                                                 Note that units for the windows have
%                                                 to be consistent with
%                                                 units of Fs
%       params: structure with fields tapers, pad, Fs, fpass, err, trialave
%       - optional
%           tapers (precalculated tapers from dpss, or in the form [NW K] e.g [3 5]) -- optional. If not
%                                                 specified, use [NW K]=[3 5]
%            pad            (padding factor for the FFT) - optional (can take values -1,0,1,2...).
%                    -1 corresponds to no padding, 0 corresponds to padding
%                    to the next highest power of 2 etc.
%                       e.g. For N = 500, if PAD = -1, we do not pad; if PAD = 0, we pad the FFT
%                       to 512 points, if pad=1, we pad to 1024 points etc.
%                       Defaults to 0.
%           Fs   (sampling frequency) - optional. Default 1.
%           fpass    (frequency band to be used in the calculation in the form
%                                   [fmin fmax])- optional.
%                                   Default all frequencies between 0 and Fs/2
%           err  (error calculation [1 p] - Theoretical error bars; [2 p] - Jackknife error bars
%                                   [0 p] or 0 - no error bars) - optional. Default 0.
%           trialave (average over events when 1, don't average when 0) - optional. Default 0
% Output:
%       S       (triggered spectrum in form time x frequency x events for trialave=0; or in the form time x frequency trialave=1)
%       t       (times)
%       f       (frequencies)
%       Serr    (error bars) only for err(1)>=1
if nargin < 4; error('Need data, events and parameters for the windows'); end;
if nargin < 5; params=[]; end;
[tapers,pad,Fs,fpass,err,trialave,params]=getparams(params);
clear tapers pad fpass trialave
if nargout > 3 && err(1)==0;
%   Cannot compute error bars with err(1)=0. change params and run again.
    error('When Serr is desired, err(1) has to be non-zero.');
end;
data=change_row_to_column(data);
data=createdatamatc(data,E,Fs,win);
if nargout==4;
    [S,t,f,Serr]=mtspecgramc(data,movingwin,params);
else
    [S,t,f]=mtspecgramc(data,movingwin,params);
end;