set(0, 'DefaultAxesFontSize', [16] );
set(0, 'DefaultTextFontSize', [16] );
set(0, 'DefaultLineLineWidth', [2] );
set(0,'DefaultfigureColormap', jet(1024));
set(0,'DefaultAxesFontName', 'Arial');
set(0,'DefaultTextFontname', 'Arial')

addpath('/home/droumis/matclust_v1.4')
addpath(genpath('/home/droumis/matclust_v1.4'));

addpath(userpath)
addpath('/home/droumis/MATLAB');

%addpath(genpath('/opt/hippo/matclust'));
%addpath('/opt/hippo/matclust/datacompile');
addpath('/opt/hippo/linearization');
addpath('/opt/hippo/mpgread');
addpath('/data19/droumis/bob');
%addpath('/home/droumis/matclust/');
addpath('/home/droumis/MATLAB/for_demetris/');

cd('/home/droumis/MATLAB/');
%addpath('/usr/local/matclust/datacompile/PC/');
addpath('/home/droumis//MATLAB/Src/');
%addpath('/home/becky/Src/');

%addpath('/opt/hippo/DataFilter/');
%addpath('/opt/') ;
%addpath('/opt/hippo/') ;
addpath('/opt/hippo/filtering/') ;
%addpath('/opt/hippo/DataFilter/timefilters/');
%addpath('/opt/hippo/DataFilter/analysisfunctions');
%addpath('/opt/hippo/DataFilter/iterators');
%addpath('/opt/hippo/DataFilter/stats');
%addpath('/home/loren/Src/Matlab/');
addpath('/home/loren/Src/Matlab/Adaptive/Suzuki/');
addpath('/home/loren/Src/Matlab/Behavior/');
addpath('/home/loren/matlab/util/');
%addpath('/home/loren/matlab/matclust/');
addpath('/home/loren/matlab/stats/');
addpath('/home/loren/matlab/statbx/');
%addpath('/opt/hippo/matclust');
%addpath('/opt/hippo/matclust/datacompile/');
addpath('/home/mkarlsso/Src/Matlab/mpgread/');
addpath('/home/mkarlsso/Src/Matlab/mpgwrite/');
addpath('/opt/hippo/mpgread/');
addpath('/opt/hippo/linearization/');
addpath('/opt/hippo/generateDSPmap/');
% addpath('/home/droumis/matclust/');
%addpath('/data19/');
addpath('/data19/droumis/bob/');
%addpath('//data19/droumis/bob/JYB_/');
%addpath('//data19/droumis/bob/JYB/');
addpath('/home/droumis/MATLAB/Src/DFAnalysis/');
addpath('/home/droumis/MATLAB/Src/Filter/');
addpath('/home/droumis/MATLAB/Src/Iterators/');

addpath('/home/droumis/MATLAB/Src/DFScripts/');
addpath('/home/droumis/MATLAB/Src/DFScripts/Examples/');
addpath('/home/droumis/MATLAB/Src/DFScripts/Replay/');
addpath('/home/droumis/MATLAB/Src/Functions/');
%addpath('/home/droumis/MATLAB/Src/Functions/@video_reader/');
%addpath('/home/droumis/MATLAB/Src/Functions/@video_reader/private/');
addpath('/home/droumis/MATLAB/Src/DataFilter/');
addpath('/home/droumis/MATLAB/Src/DataFilter/timefilters/');
addpath('/home/droumis/MATLAB/Src/DataFilter/analysisfunctions/');
addpath('/home/droumis/MATLAB/Src/DataFilter/iterators/');
addpath('/home/droumis/MATLAB/Src/DataFilter/stats/');
addpath('/home/droumis/MATLAB/Src/NSpikeProcess/');
addpath('/home/droumis/MATLAB/Src/Plot/');
addpath('/home/droumis/MATLAB/Src/Plot/distributionPlot/');
addpath('/home/droumis/MATLAB/Src/ImageCorrection/');
addpath('/home/droumis/MATLAB/Src/Debug/');

% Dan's rotation code now in
%addpath('/home/daliu/Src/Matlab/rotation_code/');
addpath('/home/droumis/MATLAB/Src/NSpikeProcess/Dan_rotationcode/');


addpath('/home/droumis/MATLAB/Src/Plot/CuedCrossTask/');
addpath('/home/droumis/MATLAB/Src/Sequencemaker/');
% addpath('/data14/jai/DUNPHY_/');
% addpath('/data14/jai/DUNPHY/');
addpath('/home/droumis/MATLAB/Src/chronux/');
addpath('/home/droumis/MATLAB/Src/chronux/dataio/');
addpath('/home/droumis/MATLAB/Src/chronux/dataio/HowToReadNexFilesInMatlab/');
addpath('/home/droumis/MATLAB/Src/chronux/dataio/ReadingPLXandDDTfilesinMatlab/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/dataio/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/dataio/HowToReadNexFilesInMatlab/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/dataio/ReadingPLXandDDTfilesinMatlab/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/fly_track/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/fly_track/FAnalyze/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/fly_track/FAnalyze/functions/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/fly_track/FTrack/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/fly_track/FTrack/functions/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/locfit/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/locfit/Book/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/locfit/Neuro/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/locfit/m/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/old/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/old/tutorial/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spectral_analysis/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spectral_analysis/continuous/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spectral_analysis/helper/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spectral_analysis/hybrid/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spectral_analysis/plots/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spectral_analysis/pointbinned/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spectral_analysis/pointtimes/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spectral_analysis/specscope/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spectral_analysis/statistical_tests/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/graphics/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/helper/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/ssg/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/utility/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/utility/datatools/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/utility/datatypes/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/utility/graphicstyles/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/utility/matlabtools/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/utility/plottypes/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/spikesort/utility/uitools/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/test/');
addpath('/home/droumis/MATLAB/Src/chronux/documentation/chronux_2_00/wave_browser/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/FAnalyze/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/FAnalyze/documentation/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/FAnalyze/documentation/TeXFiles/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/FAnalyze/functions/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/FTrack/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/FTrack/documentation/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/FTrack/documentation/TeXFiles/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/FTrack/functions/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/videoIO/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/videoIO/videoIO_2006a/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/videoIO/videoIO_2006b/');
addpath('/home/droumis/MATLAB/Src/chronux/fly_track/videoIO/videoIO_2007a/');
addpath('/home/droumis/MATLAB/Src/chronux/locfit/');
addpath('/home/droumis/MATLAB/Src/chronux/locfit/Book/');
addpath('/home/droumis/MATLAB/Src/chronux/locfit/Neuro/');
addpath('/home/droumis/MATLAB/Src/chronux/locfit/Source/');
addpath('/home/droumis/MATLAB/Src/chronux/locfit/m/');
addpath('/home/droumis/MATLAB/Src/chronux/locfit/mex/');
addpath('/home/droumis/MATLAB/Src/chronux/locfit/mex/dll/');
addpath('/home/droumis/MATLAB/Src/chronux/old/');
addpath('/home/droumis/MATLAB/Src/chronux/old/tutorial/');
addpath('/home/droumis/MATLAB/Src/chronux/spectral_analysis/');
addpath('/home/droumis/MATLAB/Src/chronux/spectral_analysis/continuous/');
addpath('/home/droumis/MATLAB/Src/chronux/spectral_analysis/helper/');
addpath('/home/droumis/MATLAB/Src/chronux/spectral_analysis/hybrid/');
addpath('/home/droumis/MATLAB/Src/chronux/spectral_analysis/plots/');
addpath('/home/droumis/MATLAB/Src/chronux/spectral_analysis/pointbinned/');
addpath('/home/droumis/MATLAB/Src/chronux/spectral_analysis/pointtimes/');
addpath('/home/droumis/MATLAB/Src/chronux/spectral_analysis/specscope/');
addpath('/home/droumis/MATLAB/Src/chronux/spectral_analysis/statistical_tests/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/graphics/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/helper/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/mex/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/sampledata/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/ssg/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/utility/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/utility/datatools/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/utility/datatypes/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/utility/graphicstyles/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/utility/matlabtools/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/utility/plottypes/');
addpath('/home/droumis/MATLAB/Src/chronux/spikesort/utility/uitools/');
addpath('/home/droumis/MATLAB/Src/chronux/test/');
addpath('/home/droumis/MATLAB/Src/chronux/wave_browser/');
addpath('/home/droumis/MATLAB/Src/chronux/wave_browser/html/');


addpath(genpath('/home/droumis/MATLAB/Src/sj_Matlab/Matlab'));
