function bool = is_spike_config(spike_config)
%IS_SPIKE_CONFIG Validate whether the input is a spike_config struct array
%
%   IS_SPIKE_CONFIG(SPIKE_CONFIG) returns true if SPIKE_CONFIG is
%   a struct array that contains valid tetrode spike recording channel
%   configuration meta-data.
%   
%   See also READ_SPIKE_CONFIG, written by smk.
%
%Written by SMK 2009 June 22.
%

% Number of channels per tetrode
NCHANNELS = 4;

% This is determined by the NSpike hardware.
DSPCHAN_ALLOWED = [
    0;  1;  2; ...
    4;  5;  6; ...
    8;  9; 10; ...
   12; 13; 14; ...
   16; 17; 18; ...
   20; 21; 22; ...
   24; 25; 26; ...
   28; 29; 30; ...
   32; 33; 34; ...
   36; 37; 38; ...
   40; 41; 42; ...
   44; 45; 46; ...
   48; 49; 50; ...
   52; 53; 54; ...
   56; 57; 58; ...
   60; 61; 62; ...
   64; 65; 66; ...
   68; 69; 70; ...
   72; 73; 74; ...
   (76:126)' ];

% This is determined by the NSpike hardware.
DSPNUM_ALLOWED = 1:8;

REQUIRED_FIELDS = { ...
    'subject'               , ...
    'day'                   , ...
    'tetrode'               , ...
    'depth'                 , ...
    'hemisphere'            , ...
    'region'                , ...
    'reference'             , ...
    'passbands'             , ...
    'thresholds'            , ...
    'dspnums'               , ...
    'dspchans'              , ...
    'Fs'                    , ...
    'sources'               };

if isempty(spike_config) && isstruct(spike_config) && ...
    all(isfield(spike_config,REQUIRED_FIELDS))
  warning('SPIKE_CONFIG struct is empty');
  bool = true;

elseif ~isstruct(spike_config) || ~all(isfield(spike_config,REQUIRED_FIELDS))
  warning('missing required field(s)');
  bool = false;

elseif ~iscellstr({spike_config(:).subject}) || ...
    ~all(strcmp({spike_config(:).subject}, ...
    regexp({spike_config(:).subject},'[a-zA-Z0-9]*','match','once')))
  warning(['subject field must be a string containing characters ' ...
      '[a-zA-Z0-9]']);
  bool = false;

elseif ~all(cellfun(@isnumeric,{spike_config(:).day})) || ...
    ~all(cellfun(@isscalar,{spike_config(:).day})) || ...
    ~all(cellfun(@isreal,{spike_config(:).day})) || ...
    ~all(cellfun(@isfinite,{spike_config(:).day})) || ...
    ~all(cellfun(@(c) (c >= 0),{spike_config(:).day})) || ...
    ~all(cellfun(@(c) (round(c) == c),{spike_config(:).day}))
  warning('day field must be a real non-negative integer scalar');
  bool = false;

elseif ~all(cellfun(@isnumeric,{spike_config(:).tetrode})) || ...
    ~all(cellfun(@isscalar,{spike_config(:).tetrode})) || ...
    ~all(cellfun(@isreal,{spike_config(:).tetrode})) || ...
    ~all(cellfun(@isfinite,{spike_config(:).tetrode})) || ...
    ~all(cellfun(@(c) (c > 0),{spike_config(:).tetrode})) || ...
    ~all(cellfun(@(c) (round(c) == c),{spike_config(:).tetrode}))
  warning('tetrode field must be a real positive integer scalar');
  bool = false;

elseif ~all(cellfun(@isnumeric,{spike_config(:).depth})) || ...
    ~all(cellfun(@isscalar,{spike_config(:).depth})) || ...
    ~all(cellfun(@isreal,{spike_config(:).depth})) || ...
    ~all(cellfun(@isfinite,{spike_config(:).depth})) || ...
    ~all(cellfun(@(c) (round(c) == c),{spike_config(:).depth}))
  warning('depth field must be an integer scalar');
  bool = false;

elseif ~iscellstr({spike_config(:).hemisphere}) || ...
    ~all(strcmp({spike_config(:).hemisphere}, ...
    regexp({spike_config(:).hemisphere},'[a-zA-Z0-9_]*','match','once')))
  warning(['hemisphere field must be a string containing characters ' ...
      '[a-zA-Z0-9_]']);
  bool = false;

elseif ~iscellstr({spike_config(:).region}) || ...
    any(cellfun(@isempty,{spike_config(:).region}))
  warning(['region field must be a non-empty string']);
  bool = false;

elseif ~all(cellfun(@isnumeric,{spike_config(:).reference})) || ...
    ~all(cellfun(@isvector,{spike_config(:).reference})) || ...
    ~all(cellfun(@(c) (size(c,1) == 1),{spike_config(:).reference})) || ...
    ~all(cellfun(@(c) (size(c,2) == 2),{spike_config(:).reference})) || ...
    ~all(cellfun(@(c) isreal(c),{spike_config(:).reference})) || ...
    ~all(cellfun(@(c) (c(1) > 0),{spike_config(:).reference})) || ...
    ~all(cellfun(@(c) (c(2) >= 0),{spike_config(:).reference}))
  warning(['reference field must be a 2-element row vector of real ' ...
      'integer values; first element (tetrode number) must be positive, ' ...
      'and second element (channel index) must be non-negative']);
  bool = false;

elseif ~all(cellfun(@isnumeric,{spike_config(:).passbands})) || ...
    ~all(cellfun(@(c) (ndims(c) == 2),{spike_config(:).passbands})) || ...
    ~all(cellfun(@(c) (size(c,1) == NCHANNELS),{spike_config(:).passbands})) || ...
    ~all(cellfun(@(c) (size(c,2) == 2),{spike_config(:).passbands})) || ...
    ~all(cellfun(@(c) isreal(c),{spike_config(:).passbands})) || ...
    ~all(cellfun(@(c) all(c(:) > 0),{spike_config(:).passbands})) || ...
    ~all(cellfun(@(c) all(c(:,2) > c(:,1)),{spike_config(:).passbands}))
  warning(['passbands field must be a %d-by-2 array of real ' ...
      'positive values; in each row, the element in the second column ' ...
      'must be greater than the element in the first column'],NCHANNELS);
  bool = false;

elseif ~all(cellfun(@isnumeric,{spike_config(:).thresholds})) || ...
    ~all(cellfun(@isvector,{spike_config(:).thresholds})) || ...
    ~all(cellfun(@(c) (size(c,1)==NCHANNELS),{spike_config(:).thresholds})) || ...
    ~all(cellfun(@(c) (size(c,2) == 1),{spike_config(:).thresholds})) || ...
    ~all(cellfun(@(c) isreal(c),{spike_config(:).thresholds})) || ...
    ~all(cellfun(@(c) all(isfinite(c)),{spike_config(:).thresholds})) || ...
    ~all(cellfun(@(c) all(c > 0),{spike_config(:).thresholds}))
  warning(['thresholds field must be a %d-element column vector of real ' ...
      'positive values'],NCHANNELS);
  bool = false;

elseif ~all(cellfun(@isnumeric,{spike_config(:).dspnums})) || ...
    ~all(cellfun(@isvector,{spike_config(:).dspnums})) || ...
    ~all(cellfun(@(c) (size(c,1)==NCHANNELS),{spike_config(:).dspnums})) || ...
    ~all(cellfun(@(c) (size(c,2) == 1),{spike_config(:).dspnums})) || ...
    ~all(cellfun(@(c) isreal(c),{spike_config(:).dspnums})) || ...
    ~all(cellfun(@(c) all(ismember(c,DSPNUM_ALLOWED)),{spike_config(:).dspnums}))
  warning(['dspnums field must be a %d-element column vector of allowed ' ...
      'values'],NCHANNELS);
  bool = false;

elseif ~all(cellfun(@isnumeric,{spike_config(:).dspchans})) || ...
    ~all(cellfun(@isvector,{spike_config(:).dspchans})) || ...
    ~all(cellfun(@(c) (size(c,1)==NCHANNELS),{spike_config(:).dspchans})) || ...
    ~all(cellfun(@(c) (size(c,2) == 1),{spike_config(:).dspchans})) || ...
    ~all(cellfun(@(c) isreal(c),{spike_config(:).dspchans})) || ...
    ~all(cellfun(@(c) all(ismember(c,DSPCHAN_ALLOWED)),{spike_config(:).dspchans}))
  warning(['dspchans field must be a %d-element column vector of allowed ' ...
      'values'],NCHANNELS);
  bool = false;

elseif ~all(cellfun(@isnumeric,{spike_config(:).Fs})) || ...
    ~all(cellfun(@(c) isa(c,'double'),{spike_config(:).Fs})) || ...
    ~all(cellfun(@isscalar,{spike_config(:).Fs})) || ...
    ~all(cellfun(@isreal,{spike_config(:).Fs})) || ...
    ~all(cellfun(@isfinite,{spike_config(:).Fs})) || ...
    ~all(cellfun(@(c) (c > 0),{spike_config(:).Fs}))
  warning('Fs field must be a real positive scalar');
  bool = false;

% tricky here: nested cellfun calls!
elseif ~all(cellfun(@iscellstr,{spike_config(:).sources})) || ...
    ~all(cellfun(@(c) numel(c) == 2,{spike_config(:).sources})) || ...
    ~all(cellfun(@(c) (exist(c{1}) == 2) & (exist(c{2}) == 2), ...
    {spike_config(:).sources})) || ...
    ~all(cellfun(@(c) isdir(fileparts(c{1})) & isdir(fileparts(c{2})), ...
    {spike_config(:).sources}))
  warning(['sources field must be a 2-element cell array of strings, each ' ...
      'of which must specifies a filename, including full path']);
  bool = false;

else
  [i1, i2] = ndgrid(1:numel(spike_config));
  pair_idx = find(i1 ~= i2);
  i1 = i1(pair_idx);
  i2 = i2(pair_idx);
  % Check that no two elements of spike_config duplicate the same
  % (subject, day, tetrode) 3-tuple
  if any(arrayfun(@(s1,s2) isequal( ...
      {s1.subject, s1.day, s1.tetrode}, ...
      {s2.subject, s2.day, s2.tetrode}),spike_config(i1),spike_config(i2)))
    bool = false;
  else
    bool = true;
  end

end
