Description of aic
Home > chronux_1_50 > locfit > aic.m
aic
PURPOSE
AIC
SYNOPSIS
function g=aic(varargin)
DESCRIPTION
 AIC
 Usage: g=aic(varargin)
 Author: Catherine Loader.
CROSS-REFERENCE INFORMATION
This function calls:
locfit Smoothing noisy data using Local Regression and Likelihood.
rsum function to extract log-likelihood and degrees-of-freedom
This function is called by:
aicplot Computes and plots the -2*AIC
SOURCE CODE
function g=aic(varargin)
% AIC
%
% Usage: g=aic(varargin)
%
%
% Author: Catherine Loader.
pen = 2.0;
fit = locfit(varargin{:});
rs = rsum(fit);
df0 = rs(1);
df1 = rs(2);
llk = rs(3);
ai = -2*llk + pen * df0;
g = [llk df0 df1 ai];
return;