Description of fitted
Home > chronux_1_50 > locfit > fitted.m
fitted
PURPOSE
Fitted values from a locfit object.
SYNOPSIS
function y = fitted(fit)
DESCRIPTION
 Fitted values from a locfit object.
 Usage:y = fitted(fit)
 Input arguments:
   fit - the locfit() fit.
  Author: Catherine Loader.
CROSS-REFERENCE INFORMATION
This function calls:
predict Interpolate a fit produced by locfit().
This function is called by:
fig6_4 Local Regression and Likelihood, Figure 6.4.
fig6_5 Local Regression and Likelihood, Figure 6.5.
fig8_1 Local Regression and Likelihood, Figure 8.1.
fig8_3 Local Regression and Likelihood, Figure 8.3.
lf_censor Censored local regression using normal assumption.
SOURCE CODE
function y = fitted(fit)
% Fitted values from a locfit object.
%
% Usage:y = fitted(fit)
%
% Input arguments:
%   fit - the locfit() fit.
%
%  Author: Catherine Loader.
y = predict(fit,'d','restyp','fit');
return;