Description of gcv
Home > chronux_1_50 > locfit > gcv.m
gcv
PURPOSE
generalized cross-validation.
SYNOPSIS
function g=gcv(varargin)
DESCRIPTION
 generalized cross-validation.
 Usage: g=gcv(varargin)
 Author: Catherine Loader.
CROSS-REFERENCE INFORMATION
This function calls:
locfit Smoothing noisy data using Local Regression and Likelihood.
rsum function to extract log-likelihood and degrees-of-freedom
This function is called by:
gcvplot Computes and plots the Generalized Cross-Validation score (GCV) for local fits with different smoothing parameters.
SOURCE CODE
function g=gcv(varargin)
% generalized cross-validation.
%
% Usage: g=gcv(varargin)
%
%
% Author: Catherine Loader.
fit = locfit(varargin{:});
rs = rsum(fit);
df0 = rs(1);
df1 = rs(2);
llk = rs(3);
n = size(fit{1}{1},1);
gc = -2*n*llk/((n-df0)^2);
g = [llk df0 df1 gc];
return;