Description of lfplot
Home > chronux_1_50 > locfit > lfplot.m
lfplot
PURPOSE
Plot (for one or two dimensions) a locfit() fit.
SYNOPSIS
function lfplot(varargin)
DESCRIPTION
 Plot (for one or two dimensions) a locfit() fit.
 Usage:
   fit = locfit(x,y);
   lfplot(fit);
 Plot the fitted smooth curve, and add a scatterplot of the data.
 Required argument:
   fit  (produced by locfit()).
 Optional arguments:
   'nodata'  - don't add data to plot.
   'contour' - for 2-d predictors, use contour instead of surf.
   'direct'  - fit directly, instead of using interpolation
               (see the predict() function).
 To add confidence bands, use the lfband() function.
 Author: Catherine Loader.
CROSS-REFERENCE INFORMATION
This function calls:
invlink inverse link function for locfit.
lfmarg computes grid margins from a locfit object, used for plotting.
plotbyfactor helper function
predict Interpolate a fit produced by locfit().
This function is called by:
den_jack Function to compute smooth estimates of the mean of x using locfit,
fig11_4 Local Regression and Likelihood, Figure 11.4.
fig11_5 Local Regression and Likelihood, Figure 11.5.
fig2_2 Local Regression and Likelihood, Figure 2.2.
fig2_3 Local Regression and Likelihood, Figure 2.3.
fig2_4 Local Regression and Likelihood, Figure 3.1.
fig2_5 Local Regression and Likelihood, Figure 2.3.
fig3_1 Local Regression and Likelihood, Figure 3.1.
fig4_1 Local Regression and Likelihood, Figure 4.1.
fig4_2 Local Regression and Likelihood, Figure 4.2.
fig5_1 Local Regression and Likelihood, Figure 5.1.
fig5_2 Local Regression and Likelihood, Figure 5.2.
fig5_3 Local Regression and Likelihood, Figure 5.3.
fig5_4 Local Regression and Likelihood, Figure 5.4.
fig6_2 Local Regression and Likelihood, Figure 6.2.
fig6_3 Local Regression and Likelihood, Figure 6.3.
fig6_5 Local Regression and Likelihood, Figure 6.5.
fig6_7 Local Regression and Likelihood, Figure 6.6.
fig7_1 Local Regression and Likelihood, Figure 7.1.
fig7_2 Local Regression and Likelihood, Figure 7.2.
fig7_3 Local Regression and Likelihood, Figure 7.3.
fig7_4 Local Regression and Likelihood, Figure 7.4.
fig8_1 Local Regression and Likelihood, Figure 8.1.
fig8_3 Local Regression and Likelihood, Figure 8.3.
fig9_2 Local Regression and Likelihood, Figure 9.2.
lfex1 Local Estimation a spike firing rate (in spikes per unit time).
lfex2 Model the success probability of successive trials of a monkey
lfgui LFGUI M-file for lfgui.fig
scb Simultaneous Confidence Bands
SOURCE CODE
function lfplot(varargin)
% Plot (for one or two dimensions) a locfit() fit.
%
% Usage:
%   fit = locfit(x,y);
%   lfplot(fit);
%
% Plot the fitted smooth curve, and add a scatterplot of the data.
%
% Required argument:
%   fit  (produced by locfit()).
%
% Optional arguments:
%   'nodata'  - don't add data to plot.
%   'contour' - for 2-d predictors, use contour instead of surf.
%   'direct'  - fit directly, instead of using interpolation
%               (see the predict() function).
%
% To add confidence bands, use the lfband() function.
%
% Author: Catherine Loader.
fit = varargin{1};
data = fit{1};
xdata = data{1};
n = size(xdata,1);
d = size(xdata,2);
fali = fit{4}{5};
ydata = data{2};
wdata = data{3};
cdata = data{4};
if length(cdata)==1 ; cdata = zeros(n,1); end;
showdata = (fit{2}{8}==0);
ppargs = {};
type = 's';
na = 2;
while na <= length(varargin)
  inc = 0;
  if (strcmp(varargin{na},'contour'))
    type = 'c';
    inc = 1;
  end;
  if (strcmp(varargin{na},'nodata'))
    showdata = 0;
    inc = 1;
  end;
  if (strcmp(varargin{na},'direct'))
    ppargs = {ppargs{:} 'direct'};
    inc = 1;
  end;
  if (inc==0)
    error('Unknown Input',varargin{na});
  end;
  na = na+inc;
end;
xfit = lfmarg(fit);
yfit = predict(fit,xfit,ppargs{:});
yfit = invlink(yfit,fali);
fam = mod(fali(1),64);
if (fam>4)
  ydata = ydata ./ wdata;
end;
if (d==1)
  plot(xfit{1},yfit);
  if (showdata)
    hold on;
     if (length(ydata)==1); ydata = zeros(n,1); end;
    plotbyfactor(xdata,ydata,cdata);
    hold off;
    end;
end;
if (d==2)
  x1 = xfit{1};
  x2 = xfit{2};
  yfit = reshape(yfit,length(x1),length(x2));
  if (type=='c')
    [C h] = contour(x1,x2,yfit');
    clabel(C,h);
    if (showdata)
      hold on;
      plotbyfactor(xdata(:,1),xdata(:,2),cdata);
      hold off;
    end;
  else
    surf(x1,x2,yfit');
  end;
end;
return;