Description of rsum
Home > chronux_1_50 > locfit > rsum.m
rsum
PURPOSE
function to extract log-likelihood and degrees-of-freedom
SYNOPSIS
function z = rsum(fit)
DESCRIPTION
 function to extract log-likelihood and degrees-of-freedom
 from locfit fit.
 order of returned vector:   df0 df1 llk.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
aic AIC
gcv generalized cross-validation.
lcv likelihood cross-validation.
lf_censor Censored local regression using normal assumption.
SOURCE CODE
function z = rsum(fit)
% function to extract log-likelihood and degrees-of-freedom
% from locfit fit.
%
% order of returned vector:   df0 df1 llk.
%
fp = fit{4};
gf = fp{6};
z = gf([2 3 1]);
return;