Description of check_consistency
Home > chronux_1_50 > helper > check_consistency.m
check_consistency
PURPOSE
Helper routine to check consistency of data dimensions
SYNOPSIS
function [N,C]=check_consistency(data1,data2,sp)
DESCRIPTION
 Helper routine to check consistency of data dimensions
 Usage: [N,C]=check_consistency(data1,data2,sp)
 Inputs:
 data1 - first dataset
 data2 - second dataset
 sp - optional argument to be input as 1 when one of the two data sets is
 spikes times stored as a 1d array.
 Outputs:
 Dimensions of the datasets - data1 or data2 (note that
    routine stops with an error message if dimensions don't match - [N,C]
    N left empty for structure arrays
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
coherencyc Multi-taper coherency,cross-spectrum and individual spectra - continuous process
coherencysegc Multi-taper coherency,cross-spectrum and individual spectra computed by segmenting two univariate time series into chunks - continuous process
cohgramc Multi-taper time-frequency coherence,cross-spectrum and individual spectra - continuous processes
coherencycpb Multi-taper coherency,cross-spectrum and individual spectra - continuous and binned point process data
coherencycpt Multi-taper coherency,cross-spectrum and individual spectra -continuous data and point process as times
coherencysegcpb Multi-taper coherency,cross-spectrum and individual spectra computed by segmenting two univariate time series into chunks - continuous and binned point process
coherencysegcpt Multi-taper coherency,cross-spectrum and individual spectra computed by segmenting two univariate time series into chunks - continuous and point process stored as times
cohgramcpb Multi-taper time-frequency coherence,cross-spectrum and individual spectra - continuous process and binned point
cohgramcpt Multi-taper time-frequency coherence,cross-spectrum and individual spectra - continuous process and point
plotsigdiff Function to plot significant differences between two time-frequency arrays X1 and X2
coherencypb Multi-taper coherency,cross-spectrum and individual spectra - binned point process
coherencysegpb Multi-taper coherency,cross-spectrum and individual spectra computed by segmenting two univariate binned point processes into chunks
cohgrampb Multi-taper time-frequency coherence,cross-spectrum and individual spectra - two binned point processes
coherencypt Multi-taper coherency - point process times
coherencysegpt Multi-taper coherency computed by segmenting two univariate point processes
cohgrampt Multi-taper time-frequency coherence - two point processes given as times
SOURCE CODE
function [N,C]=check_consistency(data1,data2,sp)
% Helper routine to check consistency of data dimensions
% Usage: [N,C]=check_consistency(data1,data2,sp)
% Inputs:
% data1 - first dataset
% data2 - second dataset
% sp - optional argument to be input as 1 when one of the two data sets is
% spikes times stored as a 1d array.
% Outputs:
% Dimensions of the datasets - data1 or data2 (note that
%    routine stops with an error message if dimensions don't match - [N,C]
%    N left empty for structure arrays
N1=[]; N2=[];
if nargin < 3 || isempty(sp); sp=0; end;
if isstruct(data1);
    C1=length(data1);
else
    [N1,C1]=size(data1);
end;
if isstruct(data2);
    C2=length(data2);
else
    [N2,C2]=size(data2);
end;
if C1~=C2; error('inconsistent dimensions'); end;
if sp==0;
   if ~isstruct(data1) && ~isstruct(data2);
      if N1~=N2; error('inconsistent dimensions'); end;
   end;
end;
N=N1; C=C1;