function batchDIOextractReroute(animaldir,animalnames,day,configfile,barrierport,rewardedwells,skipsleep)
% Extracts all epochs for each day
% animaldir - name of directory containing processed data
% animalnames - array with animals {'H1'} for one animal or {'H1'; 'H2'} for
% alternating runs
% day - day of experiment
% configfile - NSpike configfile for the day, stored in configdir currently
% /data14/jai/Config/
% well - vector indicating odour used eg [1 3]
% odour - odours used for the wells, specify in same order {'orange'
% 'melon'}
% barrierport - output port used to raise barrier
% rewarded wells - reward well locations based on task structure eg [[6 7]
% skip sleep - do not process sleep sessions

if (nargin < 4);
    barrierport=[];
end


% get the current directory to go back to after the function is done
currentdir = pwd;

% ---- File loading ----
% See if day number needs 0
dsz = '';
if (day < 10)
    dsz = '0';
end

% Specify data directory and load the file
animalname = animaldir(1:end-1);
%datadir = '/data14/jai/';
% change to /data18

datadir = '/data14/jai/';
%datadir = '/home/daliu/tmp/';

% Converts the day and epoch into text
dayt = num2str(day);

sfilename = strcat(datadir,animaldir,'/',animalname,'DIO',dsz,dayt,'.mat');

% Load the mat file
eval(['load ', sfilename]);

% load the times file, either automatically generated by NSpike process or
% manually generated with maketimesfile.m, which helps if there are breaks
% in the data

tfilename = strcat(datadir,animaldir(1:end-1),'/',animaldir(1:end-1),dsz,dayt,'/','times.mat');

eval(['load ', tfilename]);


% Get number of epochs

epoch = size(DIO{1,day},2);

% find which epochs are run epochs based on times.mat

runepoch = find(not(cellfun('isempty', strfind(names,'Run'))))-1;
sleepepoch = find(not(cellfun('isempty', strfind(names,'Sleep'))))-1;

% runepoch =[1:6];
% sleepepoch=[];

% Process all epochs

Data={};
for i=day;
    if skipsleep==1
        processepochs=runepoch;
        
    else processepochs=1:epoch;
    end
    
    for j=1:length(processepochs);
        % calls the ReturnHome version of DIO process
        % values for room 542D in 19A neuroscience building
        if any(runepoch==processepochs(j));
            pixdim=1.08;
        else pixdim=0.42;
        end
        
        % TMP version fixes repeated entries to reward well issue
        Epochdata=RerouteProcess_TMP(animaldir,animalnames,i,processepochs(j),configfile,pixdim,barrierport,runepoch,sleepepoch,ranges,rewardedwells);
        
        % calls find correct well version
        %Epochdata=DIOprocess(animaldir,i,j,configfile,wells,odour);
        Data{1,i}{1,processepochs(j)}=Epochdata;
        
    end
end


% change to that directory and saves the figure with file name
% animal_day_epoch

fileoutdir=strcat(datadir,animaldir,'/');

cd(fileoutdir);
% filename = strcat(animalname,'_',dsz,dayt,'.mat');
% save(filename,'Data');

data=Data;
filename = strcat(animalname,'data',dsz,dayt,'.mat');
save(filename,'data');

