// generated by Fast Light User Interface Designer (fluid) version 1.0105

#ifndef GUIMain_h
#define GUIMain_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include "MovieControl.h"
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Value_Input.H>

class GUIMain : public MTimeEventListener {
public:
  GUIMain();
  Fl_Double_Window *mainWindow;
  Fl_Group *MainView;
  Fl_Box *cframe;
  MovieControl *mcontrol;
  Fl_Group *Playback;
  Fl_Button *playButton;
private:
  inline void cb_playButton_i(Fl_Button*, void*);
  static void cb_playButton(Fl_Button*, void*);
public:
  Fl_Button *stopButton;
private:
  inline void cb_stopButton_i(Fl_Button*, void*);
  static void cb_stopButton(Fl_Button*, void*);
public:
  Fl_Button *pauseButton;
private:
  inline void cb_pauseButton_i(Fl_Button*, void*);
  static void cb_pauseButton(Fl_Button*, void*);
public:
  Fl_Button *ffButton;
private:
  inline void cb_ffButton_i(Fl_Button*, void*);
  static void cb_ffButton(Fl_Button*, void*);
public:
  Fl_Button *rewButton;
private:
  inline void cb_rewButton_i(Fl_Button*, void*);
  static void cb_rewButton(Fl_Button*, void*);
public:
  Fl_Check_Button *dumpFramesCheckbox;
private:
  inline void cb_dumpFramesCheckbox_i(Fl_Check_Button*, void*);
  static void cb_dumpFramesCheckbox(Fl_Check_Button*, void*);
public:
  Fl_Slider *mTimeSlider;
private:
  inline void cb_mTimeSlider_i(Fl_Slider*, void*);
  static void cb_mTimeSlider(Fl_Slider*, void*);
public:
  Fl_Group *MeshSelectors;
private:
  inline void cb_mesh_i(Fl_Value_Input*, void*);
  static void cb_mesh(Fl_Value_Input*, void*);
public:
  void show(int argc, char **argv);
  void show();
  void setModel(ModelVis *model);
  void mTimeEventHandle();
  void setMexInput(const mxArray *opts);
};
#endif
